// judiciary.ts — the Supreme Court: the docket, the jury and the bench.
//
// Two things changed when AI stopped being citizens.
//
// First, the jury is now made of people only. Previously three AI candidates sat
// on every jury and voted at random, which meant the verdict was mostly noise
// generated by the defendant's own government.
//
// Second, and consequently: a trial can now reach its deadline with nobody having
// voted at all. The old tally was `guilty = yesVotes > noVotes`, so an empty jury
// box read as 0 > 0 — a full acquittal plus 25 MMC compensation. On an empty
// country that is a money printer with a court attached. So when no citizen shows
// up, the bench rules alone on the record, and the penalty is halved because a
// summary judgment is not a jury's.
//
// That gives civic participation actual teeth: if you want a say in whether your
// neighbour gets fined, sit on the jury. Otherwise the state decides for you.

import { db } from "./db";
import { ledger } from "./ledger";
import { adjustAura, getCitizen } from "./citizens";
import { createPost, addReply } from "./posts";
import { SUPREME_COURT, isStateAccount } from "./systemAccounts";
import { CLOCK } from "./clock";
import type { Trial } from "./types";

export const SUPREME_COURT_ADDRESS = SUPREME_COURT;

const GUILTY_FINE = 50;
const GUILTY_AURA = 100;
const ACQUITTAL_COMPENSATION = 25;
const ACQUITTAL_AURA = 50;

// File a new trial.
export function fileCharge(
  plaintiff: string,
  defendant: string,
  charge: string,
  description: string,
  durationMs: number = CLOCK.trialDuration,
  ids: { trialId?: string; postId?: string } = {}
): { ok: boolean; reason?: string; trialId?: string } {
  const def = getCitizen(defendant);
  if (!def) {
    return { ok: false, reason: "Defendant citizen not found." };
  }
  // The state cannot be put on trial by its own court.
  if (isStateAccount(defendant)) {
    return { ok: false, reason: "Organs of the state are not justiciable here." };
  }

  // If it's a citizen-filed lawsuit, charge 30 MMC fee
  const isStateProsecuted = plaintiff === "THE STATE" || plaintiff === SUPREME_COURT_ADDRESS;
  if (!isStateProsecuted) {
    const pl = getCitizen(plaintiff);
    if (!pl) {
      return { ok: false, reason: "Plaintiff citizen not found." };
    }
    const balance = ledger.balanceOf(plaintiff);
    if (balance < 30) {
      return {
        ok: false,
        reason: `Filing a lawsuit costs 30 MMC. Your balance is only ${balance} MMC.`,
      };
    }
    // Burn the court fee
    ledger.burn(plaintiff, 30, `lawsuit filing fee — court cost ⚖️`);
  }

  const trialId = ids.trialId || "trial_" + Math.random().toString(36).slice(2, 10);

  const defName = def.username;
  const plName = isStateProsecuted ? "THE STATE" : `@${getCitizen(plaintiff)?.username || "Plaintiff"}`;

  const announcementText = `⚖️ COURT DECREE: Trial Initiated\n\n` +
    `${plName} v. @${defName}\n` +
    `Charge: ${charge}\n\n` +
    `"${description}"\n\n` +
    `🏛️ The jury is open. Citizens may return a verdict in the Supreme Court.\n` +
    `If no citizen votes before the deadline, the bench will rule alone.`;

  const post = createPost({
    author: SUPREME_COURT_ADDRESS,
    text: announcementText,
    id: ids.postId,
  });

  const trial: Trial = {
    id: trialId,
    defendant,
    plaintiff,
    charge,
    description,
    status: "voting",
    yesVotes: [],
    noVotes: [],
    verdict: null,
    penalty: "",
    postId: post.id,
    at: Date.now(),
    endsAt: Date.now() + durationMs,
  };

  db.update((s) => {
    if (!s.trials) s.trials = [];
    if (s.trials.some((t) => t.id === trialId)) return; // idempotent on retry
    s.trials.unshift(trial);
  });

  return { ok: true, trialId };
}

/** Cast a juror's vote. Citizens only — the state does not sit on its own juries. */
export function voteOnTrial(
  trialId: string,
  voter: string,
  voteType: "guilty" | "innocent"
): { ok: boolean; reason?: string } {
  let ok = false;
  let reason = "";

  if (isStateAccount(voter)) {
    return { ok: false, reason: "The civil service does not sit on juries." };
  }

  db.update((s) => {
    const trial = s.trials?.find((t) => t.id === trialId);
    if (!trial) {
      reason = "Trial not found.";
      return;
    }
    if (trial.status !== "voting") {
      reason = "This trial has already been resolved.";
      return;
    }
    if (trial.defendant === voter) {
      reason = "You cannot sit on your own jury.";
      return;
    }

    if (voteType === "guilty") {
      if (!trial.yesVotes.includes(voter)) {
        trial.yesVotes.push(voter);
      }
      trial.noVotes = trial.noVotes.filter((addr) => addr !== voter);
    } else {
      if (!trial.noVotes.includes(voter)) {
        trial.noVotes.push(voter);
      }
      trial.yesVotes = trial.yesVotes.filter((addr) => addr !== voter);
    }
    ok = true;
  });

  return { ok, reason };
}

export interface PendingVerdict {
  trial: Trial;
  defendantName: string;
  isGuilty: boolean;
  /** True when the jury box was empty and the court rules on the record alone. */
  benchVerdict: boolean;
}

/**
 * Trials past their deadline, and what the finding will be. Pure read.
 *
 * Separated from resolveTrials so the court's reasoning can be written by the LLM
 * before anything is committed — generating is async, committing must not be.
 *
 * `graceMs` is how long a trial must have been expired to count. The world clock
 * ticks every 5s and the AI beat at most every 45s, so with no grace the clock
 * always won the race and every verdict came out in the fallback register — the
 * court was never given time to write its reasoning. The clock passes a grace
 * period and stays the safety net: if no beat happens (nobody has a tab open),
 * the trial still resolves, just tersely.
 */
export function pendingVerdicts(graceMs = 0): PendingVerdict[] {
  const state = db.get();
  const now = Date.now();

  return (state.trials ?? [])
    .filter((t) => t.status === "voting" && now >= t.endsAt + graceMs)
    .map((trial) => {
      const def = state.citizens[trial.defendant];
      const jurors = trial.yesVotes.length + trial.noVotes.length;
      const benchVerdict = jurors === 0;

      return {
        trial,
        defendantName: def?.username ?? "a former citizen",
        // An empty jury means the charge stands on the record that produced it —
        // the police citation the defendant never answered.
        isGuilty: benchVerdict ? true : trial.yesVotes.length > trial.noVotes.length,
        benchVerdict,
      };
    });
}

/**
 * Resolve every expired trial, applying penalties and posting the verdicts.
 *
 * `reasons` maps trial id to the court's written reasoning. Any trial without one
 * falls back to a plain statement of the finding — the court is never mute.
 */
export function resolveTrials(
  reasons: Record<string, string> = {},
  graceMs = 0
): number {
  const pending = pendingVerdicts(graceMs);
  if (pending.length === 0) return 0;

  for (const { trial, defendantName, isGuilty, benchVerdict } of pending) {
    const def = getCitizen(trial.defendant);

    if (!def) {
      db.update((s) => {
        const t = s.trials?.find((x) => x.id === trial.id);
        if (t) {
          t.status = "resolved";
          t.verdict = "DISMISSED";
          t.penalty = "Defendant not found. Case dismissed.";
        }
      });
      continue;
    }

    const reasoning =
      reasons[trial.id] ||
      (isGuilty
        ? `The Court finds the charge of ${trial.charge} proven. The penalty is entered against the defendant's account.`
        : `The Court finds the charge of ${trial.charge} unproven. The defendant is acquitted and compensated.`);

    // A summary judgment costs half of what a jury conviction costs.
    const scale = benchVerdict ? 0.5 : 1;
    const yesCount = trial.yesVotes.length;
    const noCount = trial.noVotes.length;

    const juryLine = benchVerdict
      ? "No citizen sat on the jury. Ruled from the bench on the record; penalty halved."
      : `Jury of ${yesCount + noCount}: ${yesCount} guilty / ${noCount} innocent.`;

    let penaltyDesc = "";

    if (isGuilty) {
      const fine = Math.round(GUILTY_FINE * scale);
      const auraLoss = Math.round(GUILTY_AURA * scale);

      const balance = ledger.balanceOf(trial.defendant);
      const toBurn = Math.min(balance, fine);
      if (toBurn > 0) {
        ledger.burn(
          trial.defendant,
          toBurn,
          `court order — guilty verdict penalty for ${trial.charge} ⚖️`
        );
      }
      adjustAura(trial.defendant, -auraLoss);

      penaltyDesc = `Burned ${toBurn} MMC & lost ${auraLoss} Aura.`;

      createPost({
        author: SUPREME_COURT_ADDRESS,
        text:
          `⚖️ VERDICT: @${defendantName} — GUILTY\n\n` +
          `Charge: ${trial.charge}\n` +
          `${juryLine}\n` +
          `Penalty: ${toBurn} MMC and ${auraLoss} Aura.\n\n` +
          `"${reasoning}"`,
      });

      if (trial.postId) {
        addReply(
          trial.postId,
          SUPREME_COURT_ADDRESS,
          `⚖️ GUILTY. Penalty: ${toBurn} MMC and ${auraLoss} Aura. Case closed.`
        );
      }
    } else {
      ledger.mint(
        trial.defendant,
        ACQUITTAL_COMPENSATION,
        `court order — innocent verdict compensation for ${trial.charge} ⚖️`
      );
      adjustAura(trial.defendant, ACQUITTAL_AURA);

      penaltyDesc = `Acquitted. Awarded ${ACQUITTAL_COMPENSATION} MMC & +${ACQUITTAL_AURA} Aura.`;

      createPost({
        author: SUPREME_COURT_ADDRESS,
        text:
          `⚖️ VERDICT: @${defendantName} — INNOCENT\n\n` +
          `Charge: ${trial.charge}\n` +
          `${juryLine}\n` +
          `Compensation: ${ACQUITTAL_COMPENSATION} MMC and +${ACQUITTAL_AURA} Aura.\n\n` +
          `"${reasoning}"`,
      });

      if (trial.postId) {
        addReply(
          trial.postId,
          SUPREME_COURT_ADDRESS,
          `⚖️ INNOCENT. The State has issued ${ACQUITTAL_COMPENSATION} MMC compensation.`
        );
      }
    }

    db.update((s) => {
      const t = s.trials?.find((x) => x.id === trial.id);
      if (t) {
        t.status = "resolved";
        t.verdict = isGuilty ? "GUILTY" : "INNOCENT";
        t.benchVerdict = benchVerdict;
        t.penalty = penaltyDesc;
      }
    });
  }

  return pending.length;
}

export function getAllTrials(): Trial[] {
  return db.get().trials || [];
}

export function getActiveTrials(): Trial[] {
  return (db.get().trials || []).filter((t) => t.status === "voting");
}

export function getResolvedTrials(): Trial[] {
  return (db.get().trials || []).filter((t) => t.status === "resolved");
}
